deployment:
  tasks:
    - export DEPLOYPATH=/home/filchevw/icarddocumentation.filchevweb.com
    - /opt/cpanel/ea-nodejs20/bin/npm ci
    - /opt/cpanel/ea-nodejs20/bin/npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R dist/* $DEPLOYPATH